### ISSUE TITLE
Phasing and Versioning

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-layer0-types#7]
As outlined in the CCAMP mailing list discussion, there are many drafts which depend on the layer0-types:
a)	ietf-ccamp-wson-yang;
b)	ietf-ccamp-flexigrid-yang;
c)	ietf-ccamp-wson-tunnel; 
d)	ietf-ccamp-flexigrid-media-channel-yang;
e)	ietf-dwdm-if-param-yang;
f)	ietf-ccamp-optical-impairment-topology-yang

Two options have been identified to address this issue:
https://mailarchive.ietf.org/arch/msg/ccamp/zIPpG6RiToQ4L03MxXVOwA2USXU/
https://mailarchive.ietf.org/arch/msg/ccamp/VBej2FFUN9vkbtqgXX4eaLfsUF4/

**Comment by italobusi** [comment]
The proposals are assuming that in the first phase a set of drafts (a, b, c and d) are published as RFC, together with layer0-types, to cover the 'spectrum allocation' scenarios

If there is agreement on the phasing, then we need to understand how to "split" the work on layer0-types. I have prepared few slides describing some options: [versioning-00.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-layer0-types/files/4374340/versioning-00.pptx)

**Comment by italobusi** [comment]
This issue has been discussed during the optical-impairments draft weekly call on 2020-03-26

The preferred option is something in between the first and second option, where a new module/draft is started with the content of layer0-types which is not mature to be published in the first phase (named as something like ‘ietf-layer0-types-ext’) and, once the layer0-types is published as an RFC, to merge this module within an updated version of the layer0-types which could then be published as an RFC that updates the version 1 of layer0-types

This option has been added in slide 4: [versioning-01.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-layer0-types/files/4390041/versioning-01.pptx)

@italobusi : summarize this discussion and ask for feedbacks to the CCAMP WG mailing list

**Comment by haomianzheng** [comment]
This issue has been discussed in both impairment group and ccamp list. The decision is to remove the transponder, bandwidth parameters in the first phase of ietf-layer0-types and leave them into the second phase. 
10acf682d70a734de21a81868f4f13a2b9c1a8f3 has completed the removal of above information.

**Comment by italobusi** [comment]
I think we can close this issue
